services:
  - name: customer-service
    image: dockette/nodejs
    repository:
      image: alpine/node
      tag: latest
    port: 3001
    replicas: 1
    namespace: hugosave-services
  - name: order-service
    image: mohammedamrath/orderservice
    repository:
      image: alpine/node
      tag: latest
    port: 3002
    replicas: 1
    namespace: hugosave-services
