services:
  - name: customer-serviceq
    repository:
      image: mohammedamrath/customerservice
      tag: latest
    port: 3001
    replicas: 2
    namespace: hugosave-services
  - name: order-service
    repository:
      image: mohammedamrath/orderservice
      tag: latest
    port: 3002
    replicas: 2
    namespace: hugosave-services
