services:
  - name: customer-service
    repository:
      image: amrathmd/customerservice
      tag: latest
    port: 3001
    replicas: 1
    namespace: hugosave-services
  - name: order-service
    repository:
      image: mohammedamrath/orderservice
      tag: latest
    port: 3002
    replicas: 1
    namespace: hugosave-services
