services:
  - name: customer-service
    image: dockette/nodejs
    repository:
      image: ngnix
      tag: latest
    port: 3001
    replicas: 1
    namespace: tomato
  - name: order-service
    image: mohammedamrath/orderservice
    repository:
      image: dockette/nodejs
      tag: latest
    port: 3002
    replicas: 1
    namespace: tomato
