apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-services
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - cluster: dev
            url: https://kubernetes.default.svc
          - cluster: prod
            url: https://kubernetes.default.svc
          - cluster: test
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: "{{.cluster}}-guestbook"
    spec:
      project: my-project
      source:
        repoURL: https://github.com/amrathhugo/argo-declarative-setup.git
        targetRevision: HEAD
        path: deployments/{{.cluster}}/helm/values.yaml
      destination:
        server: "{{.url}}"
        namespace: tomato
