apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-services
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - customer: pk
            app: core
            env: dev
            url: https://kubernetes.default.svc
          - customer: pk
            app: core
            env: prod
            url: https://kubernetes.default.svc
          - customer: pk
            app: distribute
            env: dev
            url: https://kubernetes.default.svc
          - customer: sg
            app: distribute
            env: prod
            url: https://kubernetes.default.svc
          - customer: sg
            app: core
            env: dev
            url: https://kubernetes.default.svc
          - customer: sg
            app: core
            env: prod
            url: https://kubernetes.default.svc
          - customer: sg
            app: distribute
            env: dev
            url: https://kubernetes.default.svc
          - customer: sg
            app: distribute
            env: prod
            url: https://kubernetes.default.svc

  template:
    metadata:
      name: "{{.customer}}-{{.app}}-{{.env}}"
    spec:
      project: my-project
      source:
        repoURL: https://github.com/amrathhugo/argo-declarative-setup.git
        targetRevision: HEAD
        path: deployments/{{.customer}}/{{.app}}/{{.env}}/{{.customer}}-{{.app}}-{{.env}}-chart/
      destination:
        server: "{{.url}}"
        namespace: hugosave-services
